### ISSUE TITLE
Improvment: Add a badge

### ISSUE THREAD

**Issue by vvatelot** [alexanderdamiani/pytester-cov#2]
I do not know if this can be possible to add a badge to the readme...
But maybe, it is possible to do it in the comment?

You could use https://shields.io/#your-badge To make it:
- Red : < 20%
- Orange : > 20% and <50%
- Yellow : > 50% and < 70%
- Green : > 70% and < 90%
- Brightgreen : > 90%

![Exemple](https://img.shields.io/badge/pytest--coverage-99%25-brightgreen)

**Comment by alexanderdamiani** [comment]
Thanks for the suggestion, I like this idea too. I'm going to look into adding it this week.

You're also able to fork the repo and submit a pull request that does this as well.

**Comment by vvatelot** [comment]
@alexanderdamiani alright! On it!
